return {
  { "folke/noice.nvim", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "rafamadriz/friendly-snippets", enabled = false },
  { "ggandor/flit.nvim", enabled = false },
  { "ggandor/leap.nvim", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "akinsho/bufferline.nvim", enabled = false },
  { "SmiteshP/nvim-navic", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  { "tpope/vim-repeat", enabled = false },
  { "folke/neoconf.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  { "folke/flash.nvim", enabled = false },
}
